assembly_linkage.o: assembly_linkage.S
boot.o: boot.S multiboot.h x86_desc.h types.h
x86_desc.o: x86_desc.S x86_desc.h types.h
filesys.o: filesys.c filesys.h types.h sys_calls.h rtc.h keyboard.h lib.h
i8259.o: i8259.c i8259.h types.h lib.h
idt.o: idt.c x86_desc.h types.h idt.h lib.h assembly_linkage.h \
  sys_calls.h filesys.h rtc.h keyboard.h i8259.h scheduler.h
kernel.o: kernel.c multiboot.h types.h x86_desc.h lib.h i8259.h debug.h \
  tests.h idt.h paging.h constants.h keyboard.h rtc.h filesys.h \
  sys_calls.h
keyboard.o: keyboard.c keyboard.h types.h x86_desc.h idt.h lib.h i8259.h
lib.o: lib.c lib.h types.h
paging.o: paging.c paging.h constants.h types.h
rtc.o: rtc.c x86_desc.h types.h idt.h rtc.h lib.h assembly_linkage.h \
  sys_calls.h filesys.h keyboard.h i8259.h
scheduler.o: scheduler.c scheduler.h idt.h lib.h types.h
sys_calls.o: sys_calls.c sys_calls.h types.h filesys.h rtc.h keyboard.h \
  lib.h assembly_linkage.h idt.h constants.h paging.h x86_desc.h
tests.o: tests.c tests.h x86_desc.h types.h lib.h keyboard.h rtc.h \
  filesys.h sys_calls.h assembly_linkage.h idt.h
